---------------------------BD MUJERLINDA----------------------------
CREATE PLUGGABLE DATABASE PDBMUJERLINDACATS
  ADMIN USER MUJERCATSADMIN IDENTIFIED BY MUJERCATSADMIN
  ROLES = (DBA)
  FILE_NAME_CONVERT = ('/opt/oracle/oradata/IIB12IDX/', '/opt/oracle/oradata/PDBMUJERLINDACATS/');
/*Conectarse via linea de comandos y ejecutar lo siguiente
sqlplus sys/admin@//localhost:1521/IIB12IDX as sysdba
ALTER PLUGGABLE DATABASE PDBMUJERLINDACATS OPEN;
SHOW PDBS;
*/
CREATE USER "MUJERLINDA" IDENTIFIED BY "MUJERCATS" PROFILE "DEFAULT";
GRANT "CONNECT" TO "MUJERLINDA";
GRANT "RESOURCE" TO "MUJERLINDA";

CREATE TABLESPACE USERS 
    DATAFILE '/opt/oracle/oradata/PDBMUJERLINDACATS/users01.dbf' 
    SIZE 500M 
    AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

ALTER USER "MUJERLINDA" quota unlimited on "USERS";
---------------------------------------------------------------------------


CREATE TABLE FMLC_PARTICIPANTE_RIFA(
    FMLC_PARTICIPANTE NUMBER(*, 0) NOT NULL,
    FMLC_NOMBRE VARCHAR2(64 BYTE) NOT NULL,
    FMLC_APELLIDO VARCHAR2(64 BYTE) NOT NULL,
    FMLC_CELULAR VARCHAR2(32 BYTE) NOT NULL,
    FMLC_CORREO VARCHAR2(50 BYTE) NULL,
    CONSTRAINT "PK_FMLC_PARTICIPANTE" PRIMARY KEY("FMLC_PARTICIPANTE")
)TABLESPACE USERS;

COMMENT ON TABLE FMLC_PARTICIPANTE_RIFA IS 'EN ESTA TABLA ESTAN LOS PARTICIPANTES DE LAS RIFAS';
CREATE SEQUENCE FMLC_PARTICIPANTE_RIFA_TX_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

-- Tabla de Proveedor
CREATE TABLE FMLC_PROVEEDOR (
    FMLC_PRV_ID NUMBER(*, 0) NOT NULL,
    FMLC_PRV_NOMBRE VARCHAR2(32 BYTE) NOT NULL,
    FMLC_PRV_CORREO VARCHAR2(50 BYTE) NULL,
    FMLC_PRV_CELULAR VARCHAR2(50 BYTE) NULL,
    FMLC_PRV_DESCRIPCION VARCHAR2(50 BYTE) NULL,
    FMLC_PRV_TIPO VARCHAR2(50 BYTE) NULL,
    FMLC_PRV_ACTIVO CHAR(1) DEFAULT '0',
    CONSTRAINT PK_FMLC_PROVEEDOR PRIMARY KEY (FMLC_PRV_ID),
    CONSTRAINT CONST_PRV_ACTIVO_CHECK CHECK(FMLC_PRV_ACTIVO IN('1','0'))
)TABLESPACE USERS;
COMMENT ON TABLE FMLC_PROVEEDOR IS 'EN ESTA TABLA ESTAN LOS PROVEEDORES DE MUJER LINDA CATS';
CREATE SEQUENCE FMLC_PROVEEDOR_TX_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

-- Tabla de Cuentas del Proveedor
CREATE TABLE FMLC_CUENTAS_PROVEEDOR (
    FMLC_CUENTA_PRV_ID NUMBER(*, 0) NOT NULL,
    FMLC_CUENTA_PRV_BANCO VARCHAR2(32 BYTE) NOT NULL,
    FMLC_CUENTA_PRV_TIPOCUENTA VARCHAR2(50 BYTE) NULL,
    FMLC_CUENTA_PRV_NUM_CUENTA VARCHAR2(50 BYTE) NOT NULL,
    FMLC_CUENTA_PRV_DESCRIPCION VARCHAR2(50 BYTE) NULL,
    FMLC_PRV_ID NUMBER(*, 0) NOT NULL, -- Clave foránea
    CONSTRAINT PK_FMLC_CUENTAS_PROVEEDOR PRIMARY KEY (FMLC_CUENTA_PRV_ID),
    CONSTRAINT FK_FMLC_CUENTAS_PROVEEDOR_PROVEEDOR FOREIGN KEY (FMLC_PRV_ID)
        REFERENCES FMLC_PROVEEDOR (FMLC_PRV_ID) ON DELETE CASCADE
)TABLESPACE USERS;
COMMENT ON TABLE FMLC_PROVEEDOR IS 'EN ESTA TABLA ESTAN LOS CUENTAS DE PROVEEDORES DE MUJER LINDA CATS';
CREATE SEQUENCE FMLC_CUENTAS_PROVEEDOR_TX_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

-- Tabla de Rifas
CREATE TABLE FMLC_RIFA (
    FMLC_RIFA_ID NUMBER(10, 0) NOT NULL, -- ID único de la rifa
    FMLC_RIFA_NOMBRE VARCHAR2(100 BYTE) NOT NULL, -- Nombre de la rifa
    FMLC_RIFA_DESCRIPCION VARCHAR2(255 BYTE) NULL, -- Descripción de la rifa
    FMLC_RIFA_FECHA_INICIO DATE NOT NULL, -- Fecha de inicio
    FMLC_RIFA_FECHA_FIN DATE NOT NULL, -- Fecha de fin
    FMLC_RIFA_ESTADO VARCHAR2(20 BYTE) DEFAULT 'activa' NOT NULL, -- Estado (activa, finalizada, cancelada)
    FMLC_RIFA_PRECIO_BOLETO NUMBER(10, 2) NOT NULL, -- Precio de cada boleto
    FMLC_RIFA_MAX_BOLETOS NUMBER(10, 0) NULL, -- Número máximo de boletos
    FMLC_RIFA_CREADO_POR VARCHAR2(64 BYTE) NOT NULL, -- Usuario que creó la rifa
    FMLC_RIFA_FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL, -- Fecha de creación
    FMLC_RIFA_FECHA_ACTUALIZACION DATE DEFAULT SYSDATE, -- Última fecha de actualización
    CONSTRAINT PK_FMLC_RIFA PRIMARY KEY (FMLC_RIFA_ID)
)TABLESPACE USERS;
COMMENT ON TABLE FMLC_PROVEEDOR IS 'EN ESTA TABLA ESTAN LOS RIFAS REALIZADAS POR MUJER LINDA CATS';
CREATE SEQUENCE FMLC_RIFA_TX_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE TABLE FMLC_PREMIOS (
    FMLC_PREMIO_ID NUMBER(10, 0) NOT NULL, -- ID único del premio
    FMLC_RIFA_ID NUMBER(10, 0) NOT NULL, -- Rifa asociada
    FMLC_PREMIO_DESCRIPCION VARCHAR2(255 BYTE) NOT NULL, -- Descripción del premio
    FMLC_PREMIO_VALOR NUMBER(10, 2) NULL, -- Valor del premio
    FMLC_PARTICIPANTE_GANADOR_ID NUMBER(10, 0) NULL, -- Ganador del premio (puede estar vacío inicialmente)
    CONSTRAINT PK_FMLC_PREMIOS PRIMARY KEY (FMLC_PREMIO_ID),
    CONSTRAINT FK_FMLC_PREMIOS_RIFA FOREIGN KEY (FMLC_RIFA_ID) REFERENCES FMLC_RIFA (FMLC_RIFA_ID),
    CONSTRAINT FK_FMLC_PREMIOS_GANADOR FOREIGN KEY (FMLC_PARTICIPANTE_GANADOR_ID) REFERENCES FMLC_PARTICIPANTE_RIFA (FMLC_PARTICIPANTE)
)TABLESPACE USERS;
COMMENT ON TABLE FMLC_PROVEEDOR IS 'EN ESTA TABLA ESTAN LOS PREIMOS DE LAS RIFAS REALIZADAS POR MUJER LINDA CATS';
CREATE SEQUENCE FMLC_PREMIOS_TX_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;


CREATE TABLE FMLC_BOLETOS (
    FMLC_BOLETO_ID NUMBER(10, 0) NOT NULL, -- ID único del boleto
    FMLC_RIFA_ID NUMBER(10, 0) NOT NULL, -- Rifa asociada
    FMLC_PARTICIPANTE_ID NUMBER(10, 0) NOT NULL, -- Participante que compró el boleto
    FMLC_PROVEEDOR_ID NUMBER(10, 0) NOT NULL, -- Proveedor asociado al boleto
    FMLC_BOLETO_NUMERO VARCHAR2(20 BYTE) NOT NULL, -- Número o código del boleto
    FMLC_BOLETO_FECHA_COMPRA DATE DEFAULT SYSDATE NOT NULL, -- Fecha de compra
    FMLC_ESTADO_BOLETO CHAR(1) DEFAULT '0',
    CONSTRAINT PK_FMLC_BOLETOS PRIMARY KEY (FMLC_BOLETO_ID),
    CONSTRAINT FK_FMLC_BOLETOS_RIFA FOREIGN KEY (FMLC_RIFA_ID) REFERENCES FMLC_RIFA (FMLC_RIFA_ID),
    CONSTRAINT FK_FMLC_BOLETOS_PARTICIPANTE FOREIGN KEY (FMLC_PARTICIPANTE_ID) REFERENCES FMLC_PARTICIPANTE_RIFA (FMLC_PARTICIPANTE),
    CONSTRAINT FK_FMLC_BOLETOS_PROVEEDOR FOREIGN KEY (FMLC_PROVEEDOR_ID) REFERENCES FMLC_PROVEEDOR (FMLC_PRV_ID),
    CONSTRAINT CONST_BOLETO_ACTIVO_CHECK CHECK(FMLC_ESTADO_BOLETO IN('1','0'))
)TABLESPACE USERS;
COMMENT ON TABLE FMLC_PROVEEDOR IS 'EN ESTA TABLA ESTAN LOS BOLETOS DE LAS RIFAS REALIZADAS POR MUJER LINDA CATS';
CREATE SEQUENCE FMLC_BOLETOS_TX_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;